### ISSUE TITLE
adding more details into .csv

### ISSUE THREAD

**Issue by b1ack0p** [dreasgrech/DROMsM#9]
is it possible to add more details into .csv such as :

driver status
driver emulation
driver savestate

input details such as : 
players
coins
control type: what kind of controller/gamepad/joy/lightgun
buttons

monitor orientation: Vertical or Horizontal

`<driver status="good" emulation="good" savestate="supported"/>`

Controller details if game is 'lightgun' compatible or what kind of 'contoller/gamepad/joy' game supports?
https://cdn.discordapp.com/attachments/951454112078241802/955623994537693214/unknown.png

Screen position if it is 'vertical' or 'horizontal'
https://cdn.discordapp.com/attachments/951454112078241802/955624123512537189/unknown.png
`		<dipswitch name="Monitor Orientation" tag="DSW1" mask="32">
			<diplocation name="SW2" number="6"/>
			<dipvalue name="Horizontal" value="32" default="yes"/>
			<dipvalue name="Vertical" value="0"/>
		</dipswitch>`

'Player' details 
https://cdn.discordapp.com/attachments/951454112078241802/955627305869385778/unknown.png

`<input players="1" coins="4" service="yes">
			<control type="only_buttons" buttons="7"/>
		</input>`

etc?

**Comment by dreasgrech** [comment]
Done.

![image](https://user-images.githubusercontent.com/501697/160207865-f894df93-e3dd-4cd8-ac17-90a39eaa7db9.png)
